In [2]:
import pandas as pd
df =  pd.read_csv('2018_Central_Park_Squirrel_Census_-_Squirrel_Data.csv')

In [3]:
df.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086)
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,True,me,POINT (-73.9570437717691 40.794850940803904)
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,NaN,...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9768311751004 40.76671780725581)
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Juvenile,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9757249834141 40.7697032606755)
4,-73.959313,40.797533,39B-AM-1018-01,39B,AM,10182018,1,NaN,NaN,NaN,...,True,False,False,False,False,False,False,False,NaN,POINT (-73.9593126695714 40.797533370163)

In [16]:
gray_color = df[df['Primary Fur Color'] == 'Gray']

In [17]:
print(gray_color)

              X          Y Unique Squirrel ID Hectare Shift      Date  \
1    -73.957044  40.794851     37E-PM-1006-03     37E    PM  10062018
3    -73.975725  40.769703      5D-PM-1018-05     05D    PM  10182018
5    -73.956570  40.790256     33H-AM-1019-02     33H    AM  10192018
6    -73.971974  40.769305      6G-PM-1020-02     06G    PM  10202018
7    -73.960261  40.794288     35C-PM-1013-03     35C    PM  10132018
...         ...        ...                ...     ...   ...       ...
3016 -73.966290  40.784330     23C-AM-1019-01     23C    AM  10192018
3018 -73.963943  40.790868     30B-AM-1007-04     30B    AM  10072018
3019 -73.970402  40.782560     19A-PM-1013-05     19A    PM  10132018
3020 -73.966587  40.783678     22D-PM-1012-07     22D    PM  10122018
3021 -73.963994  40.789915     29B-PM-1010-02     29B    PM  10102018

      Hectare Squirrel Number       Age Primary Fur Color  \
1                           3     Adult              Gray
3                           5  Juvenile              Gray
5                           2  Juvenile              Gray
6                           2     Adult              Gray
7                           3       NaN              Gray
...                       ...       ...               ...
3016                        1     Adult              Gray
3018                        4     Adult              Gray
3019                        5     Adult              Gray
3020                        7     Adult              Gray
3021                        2       NaN              Gray

         Highlight Fur Color  ...   Kuks  Quaas  Moans Tail flags  \
1                   Cinnamon  ...  False  False  False      False
3                        NaN  ...  False  False  False      False
5                   Cinnamon  ...  False  False  False      False
6                        NaN  ...  False  False  False      False
7                   Cinnamon  ...  False  False  False      False
...                      ...  ...    ...    ...    ...        ...
3016         Cinnamon, White  ...   True  False  False      False
3018                     NaN  ...  False  False  False      False
3019                   White  ...  False  False  False      False
3020  Black, Cinnamon, White  ...  False  False  False      False
3021         Cinnamon, White  ...  False  False  False      False

     Tail twitches  Approaches  Indifferent  Runs from  Other Interactions  \
1            False       False        False       True                  me
3            False       False        False       True                 NaN
5            False       False        False      False                 NaN
6            False       False         True      False                 NaN
7            False       False        False       True                 NaN
...            ...         ...          ...        ...                 ...
3016         False       False         True      False                 NaN
3018         False       False        False       True                 NaN
3019         False       False         True      False                 NaN
3020         False       False         True      False                 NaN
3021         False       False         True      False                 NaN

                                          Lat/Long
1     POINT (-73.9570437717691 40.794850940803904)
3       POINT (-73.9757249834141 40.7697032606755)
5       POINT (-73.9565700386162 40.7902561000937)
6       POINT (-73.9719735582476 40.7693045133578)
7      POINT (-73.9602609920814 40.79428830455661)
...                                            ...
3016    POINT (-73.9662895079734 40.7843300758044)
3018    POINT (-73.9639431360458 40.7908677445466)
3019    POINT (-73.9704015859639 40.7825600069973)
3020    POINT (-73.9665871993517 40.7836775064883)
3021    POINT (-73.9639941227864 40.7899152327912)

[2473 rows x 31 columns]

In [11]:
df.describe()

                 X            Y          Date  Hectare Squirrel Number
count  3023.000000  3023.000000  3.023000e+03              3023.000000
mean    -73.967184    40.780853  1.011949e+07                 4.123718
std       0.007726     0.010285  4.246671e+04                 3.096492
min     -73.981159    40.764911  1.006202e+07                 1.000000
25%     -73.973102    40.771676  1.008202e+07                 2.000000
50%     -73.968594    40.778166  1.012202e+07                 3.000000
75%     -73.960189    40.791219  1.014202e+07                 6.000000
max     -73.949722    40.800119  1.020202e+07                23.000000

In [20]:
gray_color_count = len(df[df['Primary Fur Color'] == 'Gray'])
red_color_count = len(df[df['Primary Fur Color'] == 'Cinnamon'])
black_color_count = len(df[df['Primary Fur Color'] == 'Black'])

In [21]:
print(gray_color_count)
print(red_color_count)
print(black_color_count)

2473
392
103

In [22]:
dict = {
    'Fur Color' : ['gray' ,'cinnamon' ,'black'],
    'count' : [gray_color_count,red_color_count,black_color_count]
}

In [26]:
csv_file_df = pd.DataFrame(dict)
csv_file_df.to_csv('squirel_count.csv')